- name: configure z10
  hosts: servers
  become: true

  vars:
    packages:
      - git
      - vim
      - curl

  tasks:
    - name: ensure Git is installed
      ansible.builtin.dnf:
        name: "{{ packages }}"
        state: present
